describe('Account Management', () => {
  // Login before each test
  beforeEach(() => {
    cy.login('salome', 'salome02042003')
  })
  it('edits account details and saves', () => {
    cy.visit('https://automationteststore.com/index.php?rt=account/edit')
    cy.get('#AccountFrm_firstname').clear().type('Salome')
    cy.get('#AccountFrm_lastname').clear().type('Mekrishvili')
    cy.get('button[title="Continue"]').click()
    cy.contains('Your account has been successfully updated.').should('be.visible')
    cy.visit('https://automationteststore.com/index.php?rt=account/edit')
    cy.get('#AccountFrm_firstname').should('have.value', 'Salome')
    cy.get('#AccountFrm_lastname').should('have.value', 'Mekrishvili')
  })
  it('edits address and saves', () => {
    cy.visit('https://automationteststore.com/index.php?rt=account/address')
    cy.contains('New Address').click()
    cy.get('#AddressFrm_firstname').clear().type('Salome')
    cy.get('#AddressFrm_lastname').clear().type('Mekrishvili')
    cy.get('#AddressFrm_address_1').clear().type('Kedia 14')
    cy.get('#AddressFrm_city').clear().type('Tbilisi')
    cy.get('#AddressFrm_postcode').clear().type('0119')
    cy.get('#AddressFrm_country_id').select('Georgia')
    cy.get('#AddressFrm_zone_id').select('Imereti')
    cy.get('button[title="Continue"]').click()
    cy.contains('Your address has been successfully inserted').should('be.visible')
  })
  it('changes password and reverts', () => {
    cy.visit('https://automationteststore.com/index.php?rt=account/password')
    cy.get('input[name="current_password"]').type('salome02042003')
    cy.get('input[name="password"]').type('salo12')
    cy.get('input[name="confirm"]').type('salo12')
    cy.get('button[title="Continue"]').click()
    cy.contains('Your password has been successfully updated.').should('be.visible')
    cy.visit('https://automationteststore.com/index.php?rt=account/logout')
    cy.login('salome', 'salo12')
    cy.url().should('include', 'account/account')
    cy.visit('https://automationteststore.com/index.php?rt=account/password')
    cy.get('input[name="current_password"]').type('salo12')
    cy.get('input[name="password"]').type('salome02042003')
    cy.get('input[name="confirm"]').type('salome02042003')
    cy.get('button[title="Continue"]').click()
  })
})
